# Generated by Django 4.1.7 on 2023-03-16 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PCShop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='price',
            field=models.FloatField(default=100, verbose_name='Цена'),
            preserve_default=False,
        ),
    ]
